services:
  billing-service:
    build:
      context: ./apps/billing-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./apps/billing-service/.env
    restart: unless-stopped
