export const EQUIPMENT_PERMISSIONS = {
  EQUIPMENT_VIEW: "equipment.view",
  EQUIPMENT_CREATE: "equipment.create",
  EQUIPMENT_EDIT: "equipment.edit",
  EQUIPMENT_DELETE: "equipment.delete",
  CATEGORY_MANAGE: "category.manage",
  LOCATION_MANAGE: "location.manage",
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_CREATE: "maintenance.create",
  MAINTENANCE_EDIT: "maintenance.edit",
  MAINTENANCE_DELETE: "maintenance.delete",
  SCHEDULE_VIEW: "schedule.view",
  SCHEDULE_MANAGE: "schedule.manage",
  REPORTS_VIEW: "reports.view",
} as const;

export type EquipmentPermission =
  (typeof EQUIPMENT_PERMISSIONS)[keyof typeof EQUIPMENT_PERMISSIONS];

export const EQUIPMENT_DEFAULT_ROLES: Record<string, EquipmentPermission[]> = {
  saas_admin: Object.values(EQUIPMENT_PERMISSIONS),
  manager: [
    EQUIPMENT_PERMISSIONS.EQUIPMENT_VIEW,
    EQUIPMENT_PERMISSIONS.EQUIPMENT_CREATE,
    EQUIPMENT_PERMISSIONS.EQUIPMENT_EDIT,
    EQUIPMENT_PERMISSIONS.CATEGORY_MANAGE,
    EQUIPMENT_PERMISSIONS.LOCATION_MANAGE,
    EQUIPMENT_PERMISSIONS.MAINTENANCE_VIEW,
    EQUIPMENT_PERMISSIONS.MAINTENANCE_CREATE,
    EQUIPMENT_PERMISSIONS.MAINTENANCE_EDIT,
    EQUIPMENT_PERMISSIONS.SCHEDULE_VIEW,
    EQUIPMENT_PERMISSIONS.SCHEDULE_MANAGE,
    EQUIPMENT_PERMISSIONS.REPORTS_VIEW,
  ],
  operator: [
    EQUIPMENT_PERMISSIONS.EQUIPMENT_VIEW,
    EQUIPMENT_PERMISSIONS.EQUIPMENT_CREATE,
    EQUIPMENT_PERMISSIONS.EQUIPMENT_EDIT,
    EQUIPMENT_PERMISSIONS.MAINTENANCE_VIEW,
    EQUIPMENT_PERMISSIONS.MAINTENANCE_CREATE,
    EQUIPMENT_PERMISSIONS.MAINTENANCE_EDIT,
    EQUIPMENT_PERMISSIONS.SCHEDULE_VIEW,
  ],
  viewer: [
    EQUIPMENT_PERMISSIONS.EQUIPMENT_VIEW,
    EQUIPMENT_PERMISSIONS.MAINTENANCE_VIEW,
    EQUIPMENT_PERMISSIONS.SCHEDULE_VIEW,
    EQUIPMENT_PERMISSIONS.REPORTS_VIEW,
  ],
};
